# Generated by Django 4.1.1 on 2023-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booklog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کتاب")),
                (
                    "page",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره صفحه"
                    ),
                ),
            ],
        ),
    ]
